### ISSUE TITLE
Fetch account information

### ISSUE THREAD

**Issue by raiym** [slang800/instagram-screen-scrape#11]
Support fetching account information

**Comment by raiym** [comment]
Inspired by you I have created php scraper: https://github.com/raiym/instagram-php-scraper

**Comment by notslang** [comment]
You can get account info using https://github.com/slang800/instagram-scrape-account-stats ... I made it a separate tool because most people wouldn't need both and the [UNIX philosophy](http://www.catb.org/esr/writings/taoup/html/ch01s06.html) encourages splitting things up

And that's awesome!
