### ISSUE TITLE
Add the date?

### ISSUE THREAD

**Issue by chrisjvargo** [slang800/instagram-screen-scrape#20]
This is wonderful tool that is great for doing some instagram analytics. I especially appreciate it because their insight platform is currently only for mobile, which is terrible. 

I really would love to have the post date and time, if possible, in order to do some additional analyses. Is it easily implementable?

**Comment by notslang** [comment]
there should be a `time` field in the output (formatted as UNIX time) - can you post the command you're running and the output?

**Comment by chrisjvargo** [comment]
It's there. I am sorry I wasted your time. Thank you again for what is a
wonderfully useful tool.

**Comment by notslang** [comment]
No worries!
