### ISSUE TITLE
No more max_id param

### ISSUE THREAD

**Issue by oddmouse** [slang800/instagram-screen-scrape#9]
It looks like Instagram removed the max_id param, breaking this scraper. It seems to just return the first 20 post no matter what max_id is set to, causing an infinite loop.

**Comment by notslang** [comment]
I don't think I can reproduce this using the code in master. The issue might be that I haven't released the latest code... could you give me the output of `instagram-screen-scrape --version`?

**Comment by oddmouse** [comment]
This appears to be working fine now. Instagram must have fixed `max_id` on their end. When I posted this issue I would get the same results hitting `https://www.instagram.com/[user]/media/?max_id=[last_id]` as with `https://www.instagram.com/[user]/media`. Since the `last_id` was always the same, it caused an endless loop.
